# Form implementation generated from reading ui file 'c:\Users\jorda\OneDrive\Desktop\FINAL YEAR RFID LITERATURE\inventory-system\main.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(422, 344)
        self.btnHello = QtWidgets.QPushButton(Form)
        self.btnHello.setGeometry(QtCore.QRect(300, 310, 56, 17))
        self.btnHello.setObjectName("btnHello")
        self.btnRetrieve = QtWidgets.QPushButton(Form)
        self.btnRetrieve.setGeometry(QtCore.QRect(360, 310, 56, 17))
        self.btnRetrieve.setObjectName("btnRetrieve")
        self.textEdit = QtWidgets.QPlainTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(50, 10, 131, 16))
        self.textEdit.setObjectName("textEdit")
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setGeometry(QtCore.QRect(20, 80, 256, 192))
        self.tableView.setObjectName("tableView")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 290, 35, 10))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 10, 35, 10))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnHello.setText(_translate("Form", "Say Hello"))
        self.btnRetrieve.setText(_translate("Form", "Retrieve Item"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.label_2.setText(_translate("Form", "RFID: "))
